local Players = game:GetService("Players")

local function canPlayerDamageHumanoid(player: Player, taggedHumanoid: Humanoid): boolean

	-- If the humanoid is already dead, no need to apply more damage

	if taggedHumanoid.Health <= 0 then

		return false

	end

	-- Safe Zone Check
	local taggedCharacter = taggedHumanoid.Parent
	if taggedCharacter:GetAttribute("IsSafe") then
		return false
	end

	local taggedPlayer = Players:GetPlayerFromCharacter(taggedCharacter)

	-- If the player tagged a non-player humanoid then allow damage

	if not taggedPlayer then

		return true

	end

	if player.Neutral or taggedPlayer.Neutral then

		-- If either player is neutral (i.e. not on a team) then allow damage

		return true

	else

		-- Only allow damage if the players are not on the same team

		return player.Team ~= taggedPlayer.Team

	end

end

return canPlayerDamageHumanoid
